<?php

return array(
  array( 'value' => 'none',              'label' => __( 'None', 'cornerstone' ) ),
  array( 'value' => 'jello',             'label' => __( 'Jello', 'cornerstone' ) ),
  array( 'value' => 'pulse',             'label' => __( 'Pulse', 'cornerstone' ) ),
  array( 'value' => 'rubberBand',        'label' => __( 'Rubber Band', 'cornerstone' ) ),
  array( 'value' => 'swing',             'label' => __( 'Swing', 'cornerstone' ) ),
  array( 'value' => 'tada',              'label' => __( 'Tada', 'cornerstone' ) ),
  array( 'value' => 'wobble',            'label' => __( 'Wobble', 'cornerstone' ) ),
  array( 'value' => 'flip',              'label' => __( 'Flip', 'cornerstone' ) ),
  array( 'value' => 'flipInX',           'label' => __( 'Flip In X', 'cornerstone' ) ),
  array( 'value' => 'flipInY',           'label' => __( 'Flip In Y', 'cornerstone' ) ),
  array( 'value' => 'fadeIn',            'label' => __( 'Fade In', 'cornerstone' ) ),
  array( 'value' => 'fadeInUp',          'label' => __( 'Fade In Up', 'cornerstone' ) ),
  array( 'value' => 'fadeInDown',        'label' => __( 'Fade In Down', 'cornerstone' ) ),
  array( 'value' => 'fadeInLeft',        'label' => __( 'Fade In Left', 'cornerstone' ) ),
  array( 'value' => 'fadeInRight',       'label' => __( 'Fade In Right', 'cornerstone' ) ),
  array( 'value' => 'bounceIn',          'label' => __( 'Bounce In', 'cornerstone' ) ),
  array( 'value' => 'bounceInUp',        'label' => __( 'Bounce In Up', 'cornerstone' ) ),
  array( 'value' => 'bounceInDown',      'label' => __( 'Bounce In Down', 'cornerstone' ) ),
  array( 'value' => 'bounceInLeft',      'label' => __( 'Bounce In Left', 'cornerstone' ) ),
  array( 'value' => 'bounceInRight',     'label' => __( 'Bounce In Right', 'cornerstone' ) ),
  array( 'value' => 'rotateIn',          'label' => __( 'Rotate In', 'cornerstone' ) ),
  array( 'value' => 'rotateInUpLeft',    'label' => __( 'Rotate In Up Left', 'cornerstone' ) ),
  array( 'value' => 'rotateInUpRight',   'label' => __( 'Rotate In Up Right', 'cornerstone' ) ),
  array( 'value' => 'rotateInDownLeft',  'label' => __( 'Rotate In Down Left', 'cornerstone' ) ),
  array( 'value' => 'rotateInDownRight', 'label' => __( 'Rotate In Down Right', 'cornerstone' ) ),
  array( 'value' => 'zoomIn',            'label' => __( 'Zoom In', 'cornerstone' ) ),
  array( 'value' => 'zoomInUp',          'label' => __( 'Zoom In Up', 'cornerstone' ) ),
  array( 'value' => 'zoomInDown',        'label' => __( 'Zoom In Down', 'cornerstone' ) ),
  array( 'value' => 'zoomInLeft',        'label' => __( 'Zoom In Left', 'cornerstone' ) ),
  array( 'value' => 'zoomInRight',       'label' => __( 'Zoom In Right', 'cornerstone' ) )
);