<?php
get_template_part('framework/widgets/tabs_widget');
get_template_part('framework/widgets/tweets-widget');
get_template_part('framework/widgets/flickr-widget');
get_template_part('framework/widgets/facebook-like-widget');
get_template_part('framework/widgets/125_125');
get_template_part('framework/widgets/social_links');
get_template_part('framework/widgets/contact_info');
get_template_part('framework/widgets/recent-works-widget');